FROM ubuntu:xenial
RUN apt-get update

RUN apt-get -y install bison build-essential cmake flex git libedit-dev libllvm-3.7 llvm-3.7-dev libclang-3.7-dev python zlib1g-dev libelf-dev
RUN apt-get -y install luajit luajit-5.1-dev

COPY buildbcc.sh /buildbcc.sh
ENTRYPOINT ["/bin/sh", "/buildbcc.sh"]
